@startuml Tahub
'https://plantuml.com/sequence-diagram
skinparam backgroundColor #EEEBDC
skinparam handwritten true

title
 <u>Connect to LN Node By LN Link Protocol</u>
end title
actor User

box "LN Link" #green
activate "Client"
end box

box "Nostr Relay" #Grey
activate "Relay"
end box

box "LN Node" #green
activate "Tahub"
activate "Tapd"
activate "lnd"
end box

Tahub -> Relay : "Boadcast LN Node info"
User -> Tahub : "Request LNLink Url"
Tahub -> User : "Return LNLink Url"
User -> Client: "Config LNLink Url"
Client -> Relay: "Request LN Node info"
Relay -> Client: "Return LN Node info"

@enduml


@startuml Lnd
skinparam backgroundColor #EEEBDC
skinparam handwritten true

title
 <u>How To Make A Lightning Invoice</u>
end title
actor User

box "LN Link" #green
activate "Client"
end box

box "Nostr Relay" #Grey
activate "Relay"
end box

box "LN Node" #green
activate "Tahub"
activate "Tapd"
activate "Lnd"
end box

User -> Client: "Create Lightning Invoice"
Client -> Relay : "Send Request to LN Node"
Relay -> Tahub : "Send Request to LN Node"
Tahub -> Lnd : "Request Invoice"
Lnd -> Tahub : "Return Invoice"
Tahub -> Relay: "Return Invoice"
Relay -> Client: "Return Invoice"
Client -> User: "Show Invoice"
@enduml

@startuml Tapd
skinparam backgroundColor #EEEBDC
skinparam handwritten true

title
 <u>How To Generate a Taproot Assets Address</u>
end title
actor User

box "LN Link" #green
activate "Client"
end box

box "Nostr Relay" #Grey
activate "Relay"
end box

box "LN Node" #green
activate "Tahub"
activate "Tapd"
activate "Lnd"
end box

User -> Client: "Create Taproot Assets Address"
Client -> Relay : "Send Request to LN Node"
Relay -> Tahub : "Send Request to LN Node"
Tahub -> Tapd : "Request Address"
Tapd -> Tahub : "Return Address"
Tahub -> Relay: "Return Address"
Relay -> Client: "Return Address"
Client -> User: "Show Address"
@enduml
